version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get update
      - apt-get install -y xvfb
      - Xvfb :99 -ac &
      - export DISPLAY=:99
      - npm ci

  build:
    commands:
      - echo "Installing Maven dependencies (skipping tests)..."
      - mvn clean install -DskipTests -U
      - echo "Starting Appium tests..."
      - npm test

artifacts:
  files:
    - 'results/**/*'
  discard-paths: yes
